In [92]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [93]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [94]:
int_to_char = dict(enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [95]:
char_to_int = dict((v,i) for i,v in enumerate(alphabets))
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

##### Data Preparation

In [96]:
seq_length = 1
x = []
y = []

for i in range(len(alphabets)-seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1]
    x +=[[char_to_int[seq_in[0]]]]
    y +=[char_to_int[seq_out]]
    print(seq_in, '->', seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


In [97]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [98]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

### Prepare the output variable

In [99]:
#pip install --upgrade keras

In [100]:
from keras.utils import to_categorical

In [101]:
y_new = to_categorical(y)
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

### Prepare input varibles 

In [102]:
import numpy as np


In [103]:
x = np.reshape(x,(25,1,1))

In [104]:
x.shape

(25, 1, 1)

In [105]:
# Scaling the data
x_new = x/25
x_new

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [106]:
y_new.shape

(25, 26)

##### Create The model

In [107]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

In [108]:
model = Sequential()
model.add(Dense(25, input_shape=(1,1), activation='relu'))
model.add(LSTM(32))
model.add(Dense(26, activation='softmax'))

c:\Users\Administrator.DAI-PC2\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [109]:
#### Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


##### Train the model

In [110]:
model.fit(x_new, y_new, epochs=1000, batch_size=1)

Epoch 1/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2640
Epoch 2/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2510
Epoch 3/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2486
Epoch 4/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 3.2474
Epoch 5/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0438 - loss: 3.2509     
Epoch 6/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1483 - loss: 3.2343
Epoch 7/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0438 - loss: 3.2259   
Epoch 8/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0541 - loss: 3.2240   
Epoch 9/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0290 - loss: 3.2200   
Epoch 10/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1483 - loss: 3.2021
Epoch 11/1000
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0682 - loss: 3.1882   
Epoch 12/1000
25/25

In [111]:
model.evaluate(x_new, y_new, batch_size=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9953 - loss: 0.3639 


[0.5705016851425171, 0.9599999785423279]

##### Predict the charecter in sequence

In [112]:
new = 'V'
# Encode the data
new = char_to_int[new]
new = np.reshape(new, (1,1,1))
new = new/25
# Decode the data
int_to_char[np.argmax(model.predict(new))]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 245ms/step


'W'

#### Model For ABC input and D out

In [113]:
# Data Preparation
seq_length = 3
x = []
y = []

for i in range(len(alphabets)-seq_length):
    seq_in = alphabets[i:i + seq_length]
    seq_out = alphabets[i+seq_length]
    x.append([char_to_int[char] for char in seq_in])
    y.append([char_to_int[seq_out]])
    print(seq_in, '->', seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [114]:
x = np.reshape(x, (len(x), seq_length, 1))

In [115]:
x.shape

(23, 3, 1)

In [116]:
x_new = x/25

In [117]:
model = Sequential()
model.add(Dense(25, input_shape=(3,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation='softmax'))

In [118]:
y_new = to_categorical(y)
y_new.shape

(23, 26)

In [119]:
#### Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [120]:
model.fit(x_new, y_new, epochs=500, batch_size=1)

Epoch 1/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0000e+00 - loss: 3.2731
Epoch 2/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0354 - loss: 3.2432   
Epoch 3/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0494 - loss: 3.2261   
Epoch 4/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0442 - loss: 3.1974   
Epoch 5/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 3.1379
Epoch 6/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.0589
Epoch 7/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.0303
Epoch 8/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 3.0285
Epoch 9/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0889 - loss: 3.0069   
Epoch 10/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0623 - loss: 3.0381   
Epoch 11/500
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 2.7832
Epoch 12/500
23/23 ━━━━━

In [121]:
model.evaluate(x_new, y_new, batch_size=1)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0291


[0.05713983252644539, 1.0]

### Predictdtion new sequence

In [122]:
new = 'IJK'
# Encode the data
new = [char_to_int[char] for char in new]
print(new)
new = np.reshape(new, (1,3,1))
print(new)
new = new/25
print(new)
# Decode the data
int_to_char[np.argmax(model.predict(new))]

[8, 9, 10]
[[[ 8]
  [ 9]
  [10]]]
[[[0.32]
  [0.36]
  [0.4 ]]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step


'L'

In [123]:
model.predict(new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[4.7564175e-11, 2.4013092e-10, 3.8735844e-11, 3.4002150e-13,
        1.2991046e-08, 9.3346131e-07, 5.3531113e-07, 1.5642339e-05,
        5.0466937e-05, 5.9596985e-04, 1.1152643e-02, 9.7470462e-01,
        1.3168435e-02, 2.5267451e-04, 4.9636827e-05, 7.1053387e-06,
        8.2933548e-07, 3.8629264e-07, 9.9694386e-09, 2.3576154e-09,
        8.7411234e-10, 3.3286029e-09, 4.5505136e-08, 5.7728261e-10,
        1.7863907e-11, 2.6572199e-11]], dtype=float32)