In [1]:
pip install transformers


In [2]:
import tensorflow as tf

In [3]:
from transformers import BertTokenizer, TFBertForSequenceClassification

In [4]:
# Load pre-trained model and tokenizer
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name, num_labels=2)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [40]:
# Define the text we want to classify
texts = [' This was an amazing Product.', 'This is worst thing I have ever bought.']


In [41]:
# Tokenizer
inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='tf', max_length=30)

In [42]:
# Get the model's predixction

In [43]:
outputs = model(inputs)
predictions = tf.argmax(outputs.logits, axis=-1)

In [44]:
predictions

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [45]:
outputs

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.1246148 ,  0.07993138],
       [-0.1540581 ,  0.05174331]], dtype=float32)>, hidden_states=None, attentions=None)

In [46]:
import numpy as np
np.array(predictions)

array([1, 1])

In [47]:
# Print out the results
labels = ['Negative', 'Positive']
for text, prediction in zip(texts, predictions):
    print(f'Texts : {text}')
    print(f'Prediction  :{labels[ prediction]}')

Texts :  This was an amazing Product.
Prediction  :Positive
Texts : This is worst thing I have ever bought.
Prediction  :Positive


In [48]:
# Define the text we want to classify
texts = [' This was an amazing Product.', 'This is worst thing I have ever bought.']
# Tokenizer
inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='tf', max_length=30)
# Get the model's predixction
outputs = model(inputs)
predictions = tf.nn.softmax(outputs.logits, axis=-1)
#predictions = tf.argmax(outputs.logits, axis=-1)


In [49]:
predictions

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.449041  , 0.550959  ],
       [0.44873047, 0.55126953]], dtype=float32)>