In [12]:
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize


In [3]:
sent1 = "It is a good practice for us."
sent2 = 'It was also good to know about it'

In [56]:
print(sent1+sent2)

It is a good practice for us.It was also good to know about it


In [31]:
# count = dict()

# for word in word_tokenize(sent1):
#     #print(word)
#     if count[word] in count:
#         count[word] =1
#     else:
#         count[word] += 1

In [57]:
from nltk.tokenize import word_tokenize 


def count_word_frequencies(sentence, columns):
  words = word_tokenize(sentence.lower())
  
  # word_counts = {}
  # Create a dictionary with keys set to zero
  word_counts = {key: 0 for key in columns}
  # Count word occurrences using a set for efficiency
  for word in words:
    if word in word_counts:
      word_counts[word] += 1  # Increment count if word exists
    else:
      word_counts[word] = 1   # Initialize count to 1 for new words

  return word_counts



In [62]:
columns = set(word_tokenize(sent1.lower()) + word_tokenize(sent2.lower()))
columns
d1 = count_word_frequencies(sent1,columns)
d2 = count_word_frequencies(sent2,columns)

In [66]:
df = pd.DataFrame([d1, d2])

In [67]:
#df.fillna(0, inplace=True)

In [68]:
df

us  good  know  was  it  .  a  about  is  for  also  to  practice
0   1     1     0    0   1  1  1      0   1    1     0   0         1
1   0     1     1    1   2  0  0      1   0    0     1   1         0

In [37]:
columns = set(word_tokenize(sent1.lower()) + word_tokenize(sent2.lower()))
columns

{'.',
 'a',
 'about',
 'also',
 'for',
 'good',
 'is',
 'it',
 'know',
 'practice',
 'to',
 'us',
 'was'}

In [46]:
df2 = pd.DataFrame({

}, index=[1,2], columns=list(columns))
df2

us good know  was   it    .    a about   is  for also   to practice
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN      NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN      NaN

In [47]:
token1 = word_tokenize(sent1.lower())
token2 = word_tokenize(sent2.lower())

In [81]:
count1 = [token1.count(x) for x in df.columns]
count2 = [token2.count(x) for x in df.columns]

In [82]:
df2.iloc[0:] = count1
df2.iloc[1:] = count2


In [83]:
df2

us good know was it  .  a about is for also to practice
1  1    1    0   0  1  1  1     0  1   1    0  0        1
2  0    1    1   1  2  0  0     1  0   0    1  1        0

In [91]:
# USing library
from sklearn.feature_extraction.text import CountVectorizer
cvt = CountVectorizer()
new_data = cvt.fit_transform([sent1, sent2])
# value of count
values  = new_data.toarray()
# extract features name
columns = cvt.get_feature_names_out()
print(values)
print(columns)

[[0 0 1 1 1 1 0 1 0 1 0]
 [1 1 0 1 0 2 1 0 1 0 1]]
['about' 'also' 'for' 'good' 'is' 'it' 'know' 'practice' 'to' 'us' 'was']


In [88]:
new_df = pd.DataFrame(values, columns=columns)

In [89]:
new_df

about  also  for  good  is  it  know  practice  to  us  was
0      0     0    1     1   1   1     0         1   0   1    0
1      1     1    0     1   0   2     1         0   1   0    1

##### N-Grams

In [98]:
from sklearn.feature_extraction.text import CountVectorizer
cvt = CountVectorizer()

In [92]:
help(CountVectorizer)


Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts.
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_au

In [99]:
cvt = CountVectorizer(ngram_range=(1,2))

In [100]:
new_data = cvt.fit_transform([sent1, sent2])

In [101]:
new_data.toarray()

array([[0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
        0],
       [1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        1]], dtype=int64)

In [103]:
cvt.get_feature_names_out()

array(['about', 'about it', 'also', 'also good', 'for', 'for us', 'good',
       'good practice', 'good to', 'is', 'is good', 'it', 'it is',
       'it was', 'know', 'know about', 'practice', 'practice for', 'to',
       'to know', 'us', 'was', 'was also'], dtype=object)

In [113]:
from sklearn.feature_extraction.text import CountVectorizer
# cvt = CountVectorizer(ngram_range=(1,2))
cvt = CountVectorizer(ngram_range=(2,2))
new_data = cvt.fit_transform([sent1, sent2])
# value of count
values  = new_data.toarray()
# extract features name
columns = cvt.get_feature_names_out()
print(values)
print(columns)

[[0 0 1 1 0 1 1 0 0 1 0 0]
 [1 1 0 0 1 0 0 1 1 0 1 1]]
['about it' 'also good' 'for us' 'good practice' 'good to' 'is good'
 'it is' 'it was' 'know about' 'practice for' 'to know' 'was also']


In [112]:
new_df = pd.DataFrame(values, columns=columns)
new_df 

about it  also good  also good to  for us  good practice  \
0         0          0             0       1              1   
1         1          1             1       0              0   

   good practice for  good to  good to know  is good  is good practice  ...  \
0                  1        0             0        1                 1  ...   
1                  0        1             1        0                 0  ...   

   it was  it was also  know about  know about it  practice for  \
0       0            0           0              0             1   
1       1            1           1              1             0   

   practice for us  to know  to know about  was also  was also good  
0                1        0              0         0              0  
1                0        1              1         1              1  

[2 rows x 22 columns]